#!/bin/bash
NAME="oceantreasures"
DJANGODIR=/home/pi/oceantreasures-backend
SOCKFILE=/run/gunicorn.socket
USER=`whoami`
GROUP=`whoami`
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=backend.settings
DJANGO_WSGI_MODULE=backend.wsgi

echo "Starting $NAME as `whoami`"

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug
  --error-logfile /var/log/oceantreasures/gunicorn.err \
  --log-file /var/log/oceantreasures/gunicorn.log \
  --threads $NUM_WORKERS \
  --reload \
  --timeout 30
