# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=30)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='game.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='topic',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='game',
            name='current',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pictures',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='game',
            name='guessed_words',
            field=models.ManyToManyField(related_name='_game_guessed_words_+', to='game.Word'),
        ),
        migrations.AddField(
            model_name='game',
            name='words',
            field=models.ManyToManyField(to='game.Word'),
        ),
    ]
