# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_progress_rope_lenght'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='curr',
            field=models.IntegerField(help_text=b'This is the grey text'),
        ),
    ]
