# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170710_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='curr',
        ),
        migrations.AlterField(
            model_name='progress',
            name='max_progress',
            field=models.IntegerField(help_text=b'Number of pictures for one game'),
        ),
    ]
