# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20170712_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='pictures',
            field=models.ManyToManyField(related_name='game', to='game.Picture'),
        ),
    ]
