# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20170713_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
