# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_game_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='game',
            name='current',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
