# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170714_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='topic',
            field=models.CharField(default='Animal', max_length=30),
            preserve_default=False,
        ),
    ]
