# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='word',
            new_name='topic',
        ),
    ]
