# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20170721_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='topic',
            field=models.ManyToManyField(related_name='picture', to='game.Topic'),
        ),
    ]
