# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_picture_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='game.Topic'),
            preserve_default=False,
        ),
    ]
