# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='game.Topic'),
        ),
    ]
